In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
df=pd.read_csv("C:/Users/ELCOT/Downloads/sales_data.csv")

In [3]:
df.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450

In [4]:
df.tail()

    OrderID        Date     Product     Category  Quantity  UnitPrice
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [5]:
df.columns.tolist()

['OrderID', 'Date', 'Product', 'Category', 'Quantity', 'UnitPrice']

In [6]:
print(df.columns)

Index(['OrderID', 'Date', 'Product', 'Category', 'Quantity', 'UnitPrice'], dtype='str')

In [7]:
print("columns:",df.columns.tolist())

columns: ['OrderID', 'Date', 'Product', 'Category', 'Quantity', 'UnitPrice']

In [8]:
df.shape

(100, 6)

In [9]:
df.info

<bound method DataFrame.info of     OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]>

In [10]:
df["Product"]

0     Smartphone
1     Headphones
2         Laptop
3         Laptop
4         Tablet
         ...
95        Tablet
96    Headphones
97    Smartwatch
98    Smartwatch
99        Tablet
Name: Product, Length: 100, dtype: str

In [11]:
df[["Product","Category"]]

       Product     Category
0   Smartphone  Electronics
1   Headphones  Accessories
2       Laptop  Electronics
3       Laptop  Electronics
4       Tablet  Electronics
..         ...          ...
95      Tablet  Electronics
96  Headphones  Accessories
97  Smartwatch  Accessories
98  Smartwatch  Accessories
99      Tablet  Electronics

[100 rows x 2 columns]

In [12]:
df.loc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [13]:
df.loc[0:4]

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450

In [14]:
df.loc[[0],["Category","UnitPrice"]]

      Category  UnitPrice
0  Electronics        800

In [15]:
df.loc[0:4,["Product","Category","UnitPrice"]]

      Product     Category  UnitPrice
0  Smartphone  Electronics        800
1  Headphones  Accessories        150
2      Laptop  Electronics       1200
3      Laptop  Electronics       1200
4      Tablet  Electronics        450

In [16]:
df.iloc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [17]:
df.iloc[0,2]

'Smartphone'

In [18]:
df.iloc[0:5]

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450

In [19]:
df.iloc[0:5,0:2]

   OrderID        Date
0     1031  2026-01-01
1     1100  2026-01-02
2     1028  2026-01-02
3     1089  2026-01-02
4     1023  2026-01-02

In [20]:
df[df["Quantity"]<10]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [21]:
df[df["UnitPrice"]<1000]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[75 rows x 6 columns]

In [22]:
df[(df["Quantity"]>2) & (df["UnitPrice"]>500)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
3      1089  2026-01-02      Laptop  Electronics         3       1200
5      1072  2026-01-02  Smartphone  Electronics         4        800
8      1082  2026-01-03  Smartphone  Electronics         4        800
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
24     1087  2026-01-08      Laptop  Electronics         4       1200
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
42     1048  2026-01-15      Laptop  Electronics         3       1200
46     1044  2026-01-16      Laptop  Electronics         4       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
55     1050  2026-01-19  Smartphone  Electronics         3        800
62     1071  2026-01-21  Smartphone  Electronics         3        800
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
78     1033  2026-01-26      Laptop  Electronics         4       1200
87     1074  2026-01-28      Laptop  Electronics         3       1200
94     1007  2026-01-29  Smartphone  Electronics         4        800

In [23]:
df[(df["Quantity"]>2) | (df["UnitPrice"]>500)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
..      ...         ...         ...          ...       ...        ...
93     1035  2026-01-29      Laptop  Electronics         1       1200
94     1007  2026-01-29  Smartphone  Electronics         4        800
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[74 rows x 6 columns]

In [24]:
df[(df["Quantity"]>2) != (df["UnitPrice"]>500)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
2      1028  2026-01-02      Laptop  Electronics         2       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
7      1020  2026-01-03      Laptop  Electronics         1       1200
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
17     1061  2026-01-07  Headphones  Accessories         3        150
18     1058  2026-01-07      Laptop  Electronics         2       1200
22     1080  2026-01-08  Headphones  Accessories         3        150
23     1018  2026-01-08      Laptop  Electronics         2       1200
25     1006  2026-01-08  Smartwatch  Accessories         4        250
26     1060  2026-01-09  Smartwatch  Accessories         3        250
27     1069  2026-01-09      Tablet  Electronics         4        450
28     1093  2026-01-10      Tablet  Electronics         3        450
30     1014  2026-01-11  Smartwatch  Accessories         4        250
31     1005  2026-01-11  Smartwatch  Accessories         4        250
33     1036  2026-01-12  Headphones  Accessories         3        150
35     1032  2026-01-12  Smartphone  Electronics         1        800
38     1078  2026-01-12  Headphones  Accessories         3        150
39     1083  2026-01-14  Headphones  Accessories         3        150
40     1066  2026-01-14  Headphones  Accessories         4        150
41     1081  2026-01-15      Tablet  Electronics         4        450
43     1004  2026-01-15      Laptop  Electronics         2       1200
44     1045  2026-01-15      Tablet  Electronics         3        450
45     1075  2026-01-15  Smartwatch  Accessories         4        250
47     1038  2026-01-17      Laptop  Electronics         2       1200
49     1062  2026-01-18  Smartwatch  Accessories         4        250
50     1086  2026-01-18      Laptop  Electronics         1       1200
51     1097  2026-01-18      Laptop  Electronics         2       1200
52     1067  2026-01-18  Smartwatch  Accessories         3        250
56     1053  2026-01-20  Smartphone  Electronics         2        800
57     1002  2026-01-20  Headphones  Accessories         3        150
58     1073  2026-01-20  Smartwatch  Accessories         4        250
66     1021  2026-01-22      Laptop  Electronics         1       1200
67     1095  2026-01-22      Laptop  Electronics         1       1200
68     1092  2026-01-22      Laptop  Electronics         1       1200
75     1037  2026-01-25  Smartphone  Electronics         2        800
80     1098  2026-01-26      Tablet  Electronics         3        450
81     1010  2026-01-26      Laptop  Electronics         1       1200
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
86     1076  2026-01-28  Headphones  Accessories         3        150
88     1042  2026-01-28      Tablet  Electronics         4        450
90     1079  2026-01-29  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150
93     1035  2026-01-29      Laptop  Electronics         1       1200
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [25]:
df[(df["Quantity"]>2) == (df["UnitPrice"]>500)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
3      1089  2026-01-02      Laptop  Electronics         3       1200
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
8      1082  2026-01-03  Smartphone  Electronics         4        800
16     1027  2026-01-06      Tablet  Electronics         2        450
19     1077  2026-01-07  Headphones  Accessories         2        150
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
24     1087  2026-01-08      Laptop  Electronics         4       1200
29     1041  2026-01-10  Headphones  Accessories         2        150
32     1013  2026-01-11  Headphones  Accessories         2        150
34     1051  2026-01-12      Tablet  Electronics         1        450
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
42     1048  2026-01-15      Laptop  Electronics         3       1200
46     1044  2026-01-16      Laptop  Electronics         4       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
53     1057  2026-01-19      Tablet  Electronics         2        450
54     1011  2026-01-19  Headphones  Accessories         2        150
55     1050  2026-01-19  Smartphone  Electronics         3        800
59     1016  2026-01-21  Smartwatch  Accessories         2        250
60     1030  2026-01-21  Smartwatch  Accessories         2        250
61     1008  2026-01-21  Smartwatch  Accessories         1        250
62     1071  2026-01-21  Smartphone  Electronics         3        800
63     1022  2026-01-21  Headphones  Accessories         1        150
64     1059  2026-01-21  Headphones  Accessories         2        150
65     1034  2026-01-22  Headphones  Accessories         1        150
69     1052  2026-01-23      Laptop  Electronics         3       1200
70     1012  2026-01-23  Headphones  Accessories         1        150
71     1015  2026-01-24      Laptop  Electronics         4       1200
72     1024  2026-01-24      Tablet  Electronics         1        450
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
76     1064  2026-01-25      Tablet  Electronics         1        450
77     1070  2026-01-26  Headphones  Accessories         1        150
78     1033  2026-01-26      Laptop  Electronics         4       1200
79     1068  2026-01-26      Tablet  Electronics         2        450
82     1039  2026-01-27  Smartwatch  Accessories         1        250
85     1065  2026-01-28  Smartwatch  Accessories         1        250
87     1074  2026-01-28      Laptop  Electronics         3       1200
89     1043  2026-01-28      Tablet  Electronics         2        450
92     1096  2026-01-29  Smartwatch  Accessories         1        250
94     1007  2026-01-29  Smartphone  Electronics         4        800
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150

In [26]:
df[(df["Quantity"]>2) <= (df["UnitPrice"]>500)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
5      1072  2026-01-02  Smartphone  Electronics         4        800
..      ...         ...         ...          ...       ...        ...
92     1096  2026-01-29  Smartwatch  Accessories         1        250
93     1035  2026-01-29      Laptop  Electronics         1       1200
94     1007  2026-01-29  Smartphone  Electronics         4        800
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150

[64 rows x 6 columns]

In [27]:
df[(df["Quantity"]>2) >= (df["UnitPrice"]>500)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[83 rows x 6 columns]

In [28]:
df[df["Category"].isin(["Electronics","Furniture"])]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
16     1027  2026-01-06      Tablet  Electronics         2        450
18     1058  2026-01-07      Laptop  Electronics         2       1200
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
23     1018  2026-01-08      Laptop  Electronics         2       1200
24     1087  2026-01-08      Laptop  Electronics         4       1200
27     1069  2026-01-09      Tablet  Electronics         4        450
28     1093  2026-01-10      Tablet  Electronics         3        450
34     1051  2026-01-12      Tablet  Electronics         1        450
35     1032  2026-01-12  Smartphone  Electronics         1        800
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
41     1081  2026-01-15      Tablet  Electronics         4        450
42     1048  2026-01-15      Laptop  Electronics         3       1200
43     1004  2026-01-15      Laptop  Electronics         2       1200
44     1045  2026-01-15      Tablet  Electronics         3        450
46     1044  2026-01-16      Laptop  Electronics         4       1200
47     1038  2026-01-17      Laptop  Electronics         2       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
50     1086  2026-01-18      Laptop  Electronics         1       1200
51     1097  2026-01-18      Laptop  Electronics         2       1200
53     1057  2026-01-19      Tablet  Electronics         2        450
55     1050  2026-01-19  Smartphone  Electronics         3        800
56     1053  2026-01-20  Smartphone  Electronics         2        800
62     1071  2026-01-21  Smartphone  Electronics         3        800
66     1021  2026-01-22      Laptop  Electronics         1       1200
67     1095  2026-01-22      Laptop  Electronics         1       1200
68     1092  2026-01-22      Laptop  Electronics         1       1200
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
72     1024  2026-01-24      Tablet  Electronics         1        450
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
75     1037  2026-01-25  Smartphone  Electronics         2        800
76     1064  2026-01-25      Tablet  Electronics         1        450
78     1033  2026-01-26      Laptop  Electronics         4       1200
79     1068  2026-01-26      Tablet  Electronics         2        450
80     1098  2026-01-26      Tablet  Electronics         3        450
81     1010  2026-01-26      Laptop  Electronics         1       1200
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
87     1074  2026-01-28      Laptop  Electronics         3       1200
88     1042  2026-01-28      Tablet  Electronics         4        450
89     1043  2026-01-28      Tablet  Electronics         2        450
93     1035  2026-01-29      Laptop  Electronics         1       1200
94     1007  2026-01-29  Smartphone  Electronics         4        800
95     1026  2026-01-30      Tablet  Electronics         1        450
99     1047  2026-01-30      Tablet  Electronics         3        450

In [29]:
df[df["Category"] == "Electronics"]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
16     1027  2026-01-06      Tablet  Electronics         2        450
18     1058  2026-01-07      Laptop  Electronics         2       1200
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
23     1018  2026-01-08      Laptop  Electronics         2       1200
24     1087  2026-01-08      Laptop  Electronics         4       1200
27     1069  2026-01-09      Tablet  Electronics         4        450
28     1093  2026-01-10      Tablet  Electronics         3        450
34     1051  2026-01-12      Tablet  Electronics         1        450
35     1032  2026-01-12  Smartphone  Electronics         1        800
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
41     1081  2026-01-15      Tablet  Electronics         4        450
42     1048  2026-01-15      Laptop  Electronics         3       1200
43     1004  2026-01-15      Laptop  Electronics         2       1200
44     1045  2026-01-15      Tablet  Electronics         3        450
46     1044  2026-01-16      Laptop  Electronics         4       1200
47     1038  2026-01-17      Laptop  Electronics         2       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
50     1086  2026-01-18      Laptop  Electronics         1       1200
51     1097  2026-01-18      Laptop  Electronics         2       1200
53     1057  2026-01-19      Tablet  Electronics         2        450
55     1050  2026-01-19  Smartphone  Electronics         3        800
56     1053  2026-01-20  Smartphone  Electronics         2        800
62     1071  2026-01-21  Smartphone  Electronics         3        800
66     1021  2026-01-22      Laptop  Electronics         1       1200
67     1095  2026-01-22      Laptop  Electronics         1       1200
68     1092  2026-01-22      Laptop  Electronics         1       1200
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
72     1024  2026-01-24      Tablet  Electronics         1        450
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
75     1037  2026-01-25  Smartphone  Electronics         2        800
76     1064  2026-01-25      Tablet  Electronics         1        450
78     1033  2026-01-26      Laptop  Electronics         4       1200
79     1068  2026-01-26      Tablet  Electronics         2        450
80     1098  2026-01-26      Tablet  Electronics         3        450
81     1010  2026-01-26      Laptop  Electronics         1       1200
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
87     1074  2026-01-28      Laptop  Electronics         3       1200
88     1042  2026-01-28      Tablet  Electronics         4        450
89     1043  2026-01-28      Tablet  Electronics         2        450
93     1035  2026-01-29      Laptop  Electronics         1       1200
94     1007  2026-01-29  Smartphone  Electronics         4        800
95     1026  2026-01-30      Tablet  Electronics         1        450
99     1047  2026-01-30      Tablet  Electronics         3        450

In [30]:
df.loc[df["UnitPrice"]>100, ["Product","Category"]]

       Product     Category
0   Smartphone  Electronics
1   Headphones  Accessories
2       Laptop  Electronics
3       Laptop  Electronics
4       Tablet  Electronics
..         ...          ...
95      Tablet  Electronics
96  Headphones  Accessories
97  Smartwatch  Accessories
98  Smartwatch  Accessories
99      Tablet  Electronics

[100 rows x 2 columns]

In [31]:
df.sort_values("Product",ascending=False)

    OrderID        Date     Product     Category  Quantity  UnitPrice
99     1047  2026-01-30      Tablet  Electronics         3        450
16     1027  2026-01-06      Tablet  Electronics         2        450
44     1045  2026-01-15      Tablet  Electronics         3        450
53     1057  2026-01-19      Tablet  Electronics         2        450
41     1081  2026-01-15      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
65     1034  2026-01-22  Headphones  Accessories         1        150
33     1036  2026-01-12  Headphones  Accessories         3        150
22     1080  2026-01-08  Headphones  Accessories         3        150
63     1022  2026-01-21  Headphones  Accessories         1        150
57     1002  2026-01-20  Headphones  Accessories         3        150

[100 rows x 6 columns]

In [48]:
df.sort_values(by=["Category","Product"], ascending=[True,False])

    OrderID        Date     Product     Category  Quantity  UnitPrice
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
25     1006  2026-01-08  Smartwatch  Accessories         4        250
..      ...         ...         ...          ...       ...        ...
73     1019  2026-01-24      Laptop  Electronics         3       1200
78     1033  2026-01-26      Laptop  Electronics         4       1200
81     1010  2026-01-26      Laptop  Electronics         1       1200
87     1074  2026-01-28      Laptop  Electronics         3       1200
93     1035  2026-01-29      Laptop  Electronics         1       1200

[100 rows x 6 columns]

In [49]:
df["sheriff"] = df["Quantity"] * df["UnitPrice"]
df.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice  sheriff
0     1031  2026-01-01  Smartphone  Electronics         3        800     2400
1     1100  2026-01-02  Headphones  Accessories         2        150      300
2     1028  2026-01-02      Laptop  Electronics         2       1200     2400
3     1089  2026-01-02      Laptop  Electronics         3       1200     3600
4     1023  2026-01-02      Tablet  Electronics         4        450     1800

In [52]:
df.groupby("Category")["sheriff"].sum()

Category
Accessories     22750
Electronics    127600
Name: sheriff, dtype: int64

In [53]:
df.groupby("Category")["UnitPrice"].min()

Category
Accessories    150
Electronics    450
Name: UnitPrice, dtype: int64

In [54]:
df.groupby("Category")["Quantity"].max()

Category
Accessories    4
Electronics    4
Name: Quantity, dtype: int64

In [55]:
df.groupby("Category")["sheriff"].mean()

Category
Accessories     541.666667
Electronics    2200.000000
Name: sheriff, dtype: float64

In [58]:
df.groupby("Category")["UnitPrice"].count()

Category
Accessories    42
Electronics    58
Name: UnitPrice, dtype: int64

In [59]:
df.describe()

           OrderID    Quantity    UnitPrice      sheriff
count   100.000000  100.000000   100.000000   100.000000
mean   1050.500000    2.660000   577.000000  1503.500000
std      29.011492    1.139023   412.213782  1258.712165
min    1001.000000    1.000000   150.000000   150.000000
25%    1025.750000    2.000000   250.000000   450.000000
50%    1050.500000    3.000000   450.000000  1000.000000
75%    1075.250000    4.000000   900.000000  2400.000000
max    1100.000000    4.000000  1200.000000  4800.000000